---
- name: Gather facts about a previously created network by name
  os_networks_facts:
    auth:
      auth_url: "{{ auth_url }}"
      username: "{{ auth_user }}"
      password: "{{ auth_pwd }}"
      project_name: "{{ project }}"
    name:  "{{ network }}"
#- debug:
#   var: openstack_networks
