---
- name: Gather facts about a previously created image by name
  os_image_facts:
    auth:
      auth_url: "{{ auth_url }}"
      username: "{{ auth_user }}"
      password: "{{ auth_pwd }}"
      project_name: "{{ project }}"
    image:  "{{ image }}"
  register: osimage
- debug:
     msg:
        - "{{ osimage.ansible_facts.openstack_image.name }}::{{ osimage.ansible_facts.openstack_image.id }}"
