- name: Gather facts about a previously created network by name
  os_networks_facts:
    cloud: "{{ cloud }}"
    name:  "{{ instance_name | default('omit') }}"

# - name: test network
#   debug:
#     var: openstack_networks

- set_fact:
    os_netlist: []

- name: do os_subnets
  include: subnets.yml
  loop: "{{ openstack_networks }}"
  loop_control:
     loop_var: anet
     index_var: index

- name: define keymap
  set_fact:
    keymap:
      - sn_name: subnet_name
      - sn_id: subnet_id
      - id: network_id
      - name: network_name
      - sn_gw: subnet_gw
      - sn_cidr: subnet_cidr


- name: report PROPERTIES
  debug:
    msg:
        - "instances: {{ os_netlist | to_json }}"
        - "mappings: {{ keymap | to_json }}"
