---
- name: Gather facts about a previously created networks
  os_networks_facts:
    auth:
      auth_url: "{{ auth_url }}"
      username: "{{ auth_user }}"
      password: "{{ auth_pwd }}"
      project_name: "{{ project }}"
  register: networks
- debug:
     msg:
        - "{{ item.name }}::{{ item.id }}"
  with_items: "{{ networks.ansible_facts.openstack_networks }}"
