- hosts: 127.0.0.1
  connection: local
  gather_facts: no
  tasks:
    - command: uptime
      register: ut
    - name: report PROPERTIES
      debug:
        msg:
          - "current_time: {{ ut['stdout'][0:9] }}"
    - name: RESOURCE_ID
      debug:
        msg:
          - "resourceId: {{ ut | to_uuid }} "
    - name: report INTERNAL_PROPERTIES
      debug:
        msg:
          - "run_count: {{ run_count | int +1 }} "
      when: run_count is defined

    - name: report INTERNAL_PROPERTIES
      debug:
        msg:
          - "run_count: 1 "
      when: run_count is not defined
